import type { Config } from 'tailwindcss'

const config: Config = {
  darkMode: 'class',
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        // CSS Variable colors
        background: 'var(--background)',
        foreground: 'var(--foreground)',
        'foreground-secondary': 'var(--foreground-secondary)',
        'foreground-muted': 'var(--foreground-muted)',
        'foreground-subtle': 'var(--foreground-subtle)',
        border: 'var(--border)',
        'border-strong': 'var(--border-strong)',
        'border-subtle': 'var(--border-subtle)',
        card: 'var(--card)',
        'card-foreground': 'var(--card-foreground)',
        input: 'var(--input)',
        muted: 'var(--muted)',
        'muted-foreground': 'var(--muted-foreground)',
        // Executive palette (legacy)
        executive: {
          bg: {
            DEFAULT: '#FFFFFF',
            secondary: '#FAFBFC',
            tertiary: '#F3F4F6',
            inverse: '#111827',
          },
          text: {
            DEFAULT: '#111827',
            secondary: '#374151',
            tertiary: '#6B7280',
            inverse: '#FFFFFF',
          },
          border: {
            DEFAULT: '#E5E7EB',
            hover: '#D1D5DB',
            focus: '#111827',
            subtle: '#F3F4F6',
          },
        },
        // Primary with CSS var
        primary: {
          DEFAULT: 'var(--primary)',
          foreground: 'var(--primary-foreground)',
          50: '#F8FAFC',
          100: '#F1F5F9',
          200: '#E2E8F0',
          300: '#CBD5E1',
          400: '#94A3B8',
          500: '#64748B',
          600: '#475569',
          700: '#334155',
          800: '#1E293B',
          900: '#0F172A',
        },
        // Secondary with CSS var
        secondary: {
          DEFAULT: 'var(--secondary)',
          foreground: 'var(--secondary-foreground)',
          50: '#EEF2FF',
          100: '#E0E7FF',
          200: '#C7D2FE',
          300: '#A5B4FC',
          400: '#818CF8',
          500: '#6366F1',
          600: '#4F46E5',
          700: '#4338CA',
          800: '#3730A3',
          900: '#312E81',
        },
        // Accent with CSS var
        accent: {
          DEFAULT: 'var(--accent)',
          foreground: 'var(--accent-foreground)',
          50: '#ECFDF5',
          100: '#D1FAE5',
          200: '#A7F3D0',
          300: '#6EE7B7',
          400: '#34D399',
          500: '#10B981',
          600: '#059669',
          700: '#047857',
          800: '#065F46',
          900: '#064E3B',
        },
        priority: {
          urgent: '#DC2626',
          high: '#F59E0B',
          medium: '#6366F1',
          low: '#64748B',
          minimal: '#CBD5E1',
        },
        // Category colors
        category: {
          work: 'var(--category-work)',
          'work-bg': 'var(--category-work-bg)',
          personal: 'var(--category-personal)',
          'personal-bg': 'var(--category-personal-bg)',
          transaction: 'var(--category-transaction)',
          'transaction-bg': 'var(--category-transaction-bg)',
          newsletter: 'var(--category-newsletter)',
          'newsletter-bg': 'var(--category-newsletter-bg)',
          promotion: 'var(--category-promotion)',
          'promotion-bg': 'var(--category-promotion-bg)',
          social: 'var(--category-social)',
          'social-bg': 'var(--category-social-bg)',
          spam: 'var(--category-spam)',
          'spam-bg': 'var(--category-spam-bg)',
        },
      },
      fontFamily: {
        sans: ['var(--font-inter)', 'Inter', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Roboto', 'sans-serif'],
        mono: ['JetBrains Mono', 'Menlo', 'monospace'],
      },
      fontSize: {
        // Refined type scale
        'xs': ['12px', { lineHeight: '16px', letterSpacing: '0.01em' }],
        'sm': ['13px', { lineHeight: '18px', letterSpacing: '0' }],
        'base': ['14px', { lineHeight: '22px', letterSpacing: '-0.01em' }],
        'lg': ['16px', { lineHeight: '24px', letterSpacing: '-0.01em' }],
        'xl': ['18px', { lineHeight: '26px', letterSpacing: '-0.02em' }],
        '2xl': ['22px', { lineHeight: '28px', letterSpacing: '-0.02em' }],
        '3xl': ['28px', { lineHeight: '34px', letterSpacing: '-0.02em' }],
        // Legacy sizes
        'display': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em' }],
        'h1': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em' }],
        'h2': ['24px', { lineHeight: '32px', letterSpacing: '-0.02em' }],
        'h3': ['18px', { lineHeight: '26px', letterSpacing: '-0.01em' }],
        'h4': ['16px', { lineHeight: '24px', letterSpacing: '-0.01em' }],
        'body': ['15px', { lineHeight: '24px' }],
        'body-sm': ['14px', { lineHeight: '22px' }],
        'caption': ['13px', { lineHeight: '20px' }],
        'tiny': ['12px', { lineHeight: '16px' }],
        'overline': ['11px', { lineHeight: '16px', letterSpacing: '0.08em' }],
      },
      spacing: {
        '18': '72px',
        '22': '88px',
        '26': '104px',
        '30': '120px',
      },
      borderRadius: {
        'sm': '4px',
        'md': '6px',
        'lg': '8px',
        'xl': '12px',
        '2xl': '16px',
        '3xl': '20px',
      },
      boxShadow: {
        'card': 'var(--card-shadow)',
        'card-hover': 'var(--card-shadow-hover)',
        'premium': '0 1px 3px rgba(0, 0, 0, 0.08), 0 1px 2px rgba(0, 0, 0, 0.06)',
        'premium-lg': '0 4px 6px rgba(0, 0, 0, 0.07), 0 2px 4px rgba(0, 0, 0, 0.05)',
        'soft': '0 2px 8px -2px rgba(0, 0, 0, 0.08)',
        'medium': '0 4px 12px -4px rgba(0, 0, 0, 0.12)',
        'strong': '0 8px 24px -8px rgba(0, 0, 0, 0.16)',
        'executive-sm': '0 1px 2px rgba(0, 0, 0, 0.04)',
        'executive-md': '0 2px 8px rgba(0, 0, 0, 0.06)',
        'executive-lg': '0 4px 16px rgba(0, 0, 0, 0.08)',
        'executive-xl': '0 8px 32px rgba(0, 0, 0, 0.10)',
        'focus-ring': '0 0 0 2px var(--primary)',
      },
      transitionDuration: {
        '150': '150ms',
        '200': '200ms',
      },
    },
  },
  plugins: [],
}

export default config
